client_config_backend: settings
client_config:
  client_id: # Client id - credentials_module.json
  client_secret: # Client secret - credentials_module.json

save_credentials : True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
