client_config_backend: settings
client_config:
  client_id: 857288109561-u5vlki3lipt175aubk3qgcivkufp94rt.apps.googleusercontent.com
  client_secret: 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

save_credentials : True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
